#!/usr/bin/env python3
"""Live-fire test for the agent observability & trust commands (proposal 4.9).

Companion to test_bps.py. Runs OBSTEST.COM inside a real DOSBox-X instance
over the agent control channel and proves, end-to-end against a running
guest, that the proposal-4.9 commands report the truth:

  Phase 1 (4.9.1 + 4.9.2): arm cpu.probe on the phase-1 NOP loop body, run
     the loop (exactly LOOP_ITERS iterations), and assert debug.status shows
     the probe hit count == LOOP_ITERS — a full-speed, non-halting count.
     Then set a real BP at the same address, run, and assert it fires AND
     that debug.status reports that BP's own hit counter and live bytes_now.
     This is the C01E "fired or never reached?" disambiguation made concrete.

  Phase 2 (4.9.6): cpu.disasm the known, never-executed instruction block at
     landmark_disasm and check the decoded mnemonics, that every reported
     `bytes` field equals mem.read of the same address (the anti-fabrication
     guarantee), and that the walk lands exactly on disasm_end.

  Phase 3 (4.9.3): arm cpu.trace_ring (CS-filtered), run the distinctive
     straight-line chain, pause at a BP on landmark_trace_end, and assert
     cpu.traceback shows the chain in execution order, most-recent-last,
     ending at trace_end.

The landmark offsets are read from a fixed table in the guest at runtime
(CS:0103), so the driver never hardcodes volatile offsets.

Usage:
    python tests/agent_live/test_observability.py [--dosbox PATH] [--keep-tmp]

Exit code 0 if every phase passes; 1 otherwise.
"""

from __future__ import annotations

import argparse
import contextlib
import pathlib
import shutil
import struct
import subprocess
import sys
import tempfile
import textwrap
import time
from typing import Optional

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_DOSBOX = REPO_ROOT / "bin" / "x64" / "Debug" / "dosbox-x.exe"
OBSTEST_COM = pathlib.Path(__file__).resolve().with_name("OBSTEST.COM")

sys.path.insert(0, str(REPO_ROOT / "contrib" / "agent-client"))
from dbxagent import DbxAgent, AgentError  # noqa: E402

SIGNATURE_ADDR = 0x4F0
SIGNATURE_MAGIC = 0xBEEF


# --- helpers (shared shape with test_bps.py) ------------------------------

def _wait_for_portfile(path: pathlib.Path, timeout: float = 30.0) -> int:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if path.exists():
            text = path.read_text(encoding="ascii", errors="replace").strip()
            if text.isdigit():
                return int(text)
        time.sleep(0.1)
    raise TimeoutError(f"DOSBox-X never wrote {path}")


def _read_signature(agent: DbxAgent, timeout: float = 20.0) -> int:
    deadline = time.monotonic() + timeout
    last_err: Optional[Exception] = None
    while time.monotonic() < deadline:
        try:
            buf = agent.mem_read("physical", f"{SIGNATURE_ADDR:X}", 4)
        except AgentError as exc:
            last_err = exc
            time.sleep(0.1)
            continue
        magic, cs = struct.unpack("<HH", buf)
        if magic == SIGNATURE_MAGIC:
            return cs
        time.sleep(0.1)
    if last_err:
        raise last_err
    raise TimeoutError("OBSTEST.COM never stamped its signature")


def _drain_events(agent: DbxAgent) -> None:
    while agent.next_event(timeout=0.05) is not None:
        pass


def _wait_for_event(agent: DbxAgent, name: str, timeout: float = 8.0) -> dict:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        remaining = max(0.05, deadline - time.monotonic())
        ev = agent.next_event(timeout=remaining)
        if ev is None:
            continue
        if ev.get("event") == name:
            return ev
    raise TimeoutError(f"no {name!r} event within {timeout}s")


def _reset(agent: DbxAgent) -> None:
    """Pause, clear BPs + all observers, drain. Caller resumes."""
    agent.cpu_pause()
    _drain_events(agent)
    agent.debugger_command("BPDEL 0 *")
    agent.call("cpu.probe", points=[])
    with contextlib.suppress(Exception):
        agent.call("cpu.trace_ring", enabled=False)
    with contextlib.suppress(Exception):
        agent.call("mem.unwatch")
    _drain_events(agent)


def _write_conf(workdir: pathlib.Path) -> pathlib.Path:
    conf_text = textwrap.dedent(
        f"""\
        # Generated by tests/agent_live/test_observability.py
        [sdl]
        output=surface
        autolock=false
        windowresolution=640x400

        [dosbox]
        machine=svga_s3
        memsize=16

        [cpu]
        core=normal
        cputype=486
        cycles=fixed 5000

        [autoexec]
        mount C "{workdir}"
        C:
        OBSTEST.COM
        exit
        """
    )
    conf_path = workdir / "_test.dosbox-x.conf"
    conf_path.write_text(conf_text, encoding="utf-8")
    return conf_path


def _launch(dosbox_exe, workdir, portfile) -> subprocess.Popen:
    conf = _write_conf(workdir)
    return subprocess.Popen(
        [str(dosbox_exe), "-conf", str(conf),
         "-agent-listen", "127.0.0.1:0",
         "-agent-portfile", str(portfile), "-fastlaunch"],
        cwd=str(workdir),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


class Reporter:
    def __init__(self) -> None:
        self.results: list[tuple[str, bool, str]] = []

    def record(self, name: str, ok: bool, detail: str = "") -> None:
        self.results.append((name, ok, detail))
        print(f"[{'PASS' if ok else 'FAIL'}] {name}" + (f" :: {detail}" if detail else ""),
              flush=True)

    @property
    def all_passed(self) -> bool:
        return all(ok for _, ok, _ in self.results)


# --- phases ---------------------------------------------------------------

def phase1_probe_and_counters(agent, cs, loopbody, iters, rep) -> None:
    # 1a: probe counts every iteration at full speed, no halt.
    name = f"phase1a: cpu.probe counts {iters} loop iterations (non-halting)"
    try:
        _reset(agent)
        r = agent.call("cpu.probe", points=[f"{cs:04X}:{loopbody:04X}"])
        if r.get("armed") != 1:
            rep.record(name, False, f"probe arm reply: {r}")
        else:
            agent.cpu_run()
            _drain_events(agent)
            agent.keyboard_tap("1")
            time.sleep(1.0)   # 300 short NOPs at 5000 cyc/ms — give it a beat
            agent.cpu_pause(); _drain_events(agent)
            st = agent.call("debug.status")
            probe = st.get("probe", [])
            hit = next((p for p in probe
                        if p.get("seg") == cs and p.get("off") == loopbody), None)
            if hit is None:
                rep.record(name, False, f"probe point absent from debug.status: {probe}")
            elif hit["hits"] != iters:
                rep.record(name, False, f"probe hits={hit['hits']} expected {iters}")
            else:
                rep.record(name, True, f"probe hits == {iters}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.call("cpu.probe", points=[])
            agent.cpu_run(); _drain_events(agent)

    # 1b: a real BP at the same address fires, and debug.status reports its
    # hit counter + live bytes_now (0x90 = NOP at loopbody).
    name = "phase1b: BP hit counter + bytes_now in debug.status"
    try:
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{loopbody:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("1")
        ev = _wait_for_event(agent, "bp.hit", timeout=8.0)
        st = agent.call("debug.status")
        if st.get("cpu") != "paused":
            rep.record(name, False, f"cpu state={st.get('cpu')!r} (expected paused)")
            return
        bps = st.get("breakpoints", [])
        bp = next((b for b in bps
                   if b.get("kind") == "exec" and b.get("seg") == cs
                   and b.get("off") == loopbody), None)
        if bp is None:
            rep.record(name, False, f"exec BP absent from debug.status: {bps}")
            return
        problems = []
        if bp.get("hits", 0) < 1:
            problems.append(f"hits={bp.get('hits')}")
        bytes_now = (bp.get("bytes_now") or "").upper().split()
        if not bytes_now or bytes_now[0] != "90":
            problems.append(f"bytes_now={bp.get('bytes_now')!r} (expected first byte 90/NOP)")
        if ev.get("seg") != cs or ev.get("off") != loopbody:
            problems.append(f"bp.hit at {ev.get('seg'):04X}:{ev.get('off'):04X}")
        if problems:
            rep.record(name, False, "; ".join(problems))
        else:
            rep.record(name, True, f"hits={bp['hits']} bytes_now='{bp['bytes_now']}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def phase2_disasm(agent, cs, disasm, disasm_end, rep) -> None:
    name = "phase2: cpu.disasm decodes the known instruction block"
    # The fodder at landmark_disasm is, in source order:
    #   mov ax,1234h / add bx,ax / push bx / pop cx / nop / ret(n)
    # We don't hardcode exact encodings (assembler-dependent); we (a) require
    # this mnemonic sequence, (b) cross-check every instruction's reported
    # bytes against mem.read of the same address (proving cpu.disasm reads
    # guest memory rather than fabricating), and (c) require the decode to
    # land exactly on disasm_end.
    expected_mnemonics = ["mov", "add", "push", "pop", "nop", "ret"]
    try:
        _reset(agent)
        agent.cpu_run(); _drain_events(agent)   # CPU running; disasm is a pure read
        res = agent.call("cpu.disasm", addr=f"{cs:04X}:{disasm:04X}", count=12)
        insns = res.get("insns", [])
        if not insns:
            rep.record(name, False, "cpu.disasm returned no insns")
            return
        problems = []
        mnemonics = []
        off = disasm
        for ins in insns:
            if off >= disasm_end:
                break
            text = (ins.get("text") or "").lower()
            gotbytes = (ins.get("bytes") or "").upper().split()
            exp_csip = f"{cs:04X}:{off:04X}"
            if ins.get("cs_ip") != exp_csip:
                problems.append(f"cs_ip={ins.get('cs_ip')!r} expected {exp_csip}")
            try:
                mem = agent.mem_read("seg:off", f"{cs:04X}:{off:04X}", len(gotbytes))
                memhex = [f"{x:02X}" for x in mem]
            except Exception as exc:
                problems.append(f"mem.read failed at {exp_csip}: {exc!r}")
                memhex = []
            if memhex and memhex != gotbytes:
                problems.append(f"@{exp_csip} disasm bytes {gotbytes} != mem {memhex}")
            mnemonics.append(text.split()[0] if text.split() else "")
            off += len(gotbytes)
        if off != disasm_end:
            problems.append(f"walked to {off:04X}, expected disasm_end {disasm_end:04X}")
        if len(mnemonics) != len(expected_mnemonics) or \
           not all(exp in got for exp, got in zip(expected_mnemonics, mnemonics)):
            problems.append(f"mnemonics={mnemonics} expected ~{expected_mnemonics}")
        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"{len(mnemonics)} insns; bytes match mem.read; mnemonics {mnemonics}")
    except Exception as exc:
        rep.record(name, False, repr(exc))


def phase3_traceback(agent, cs, trace_a, trace_end, rep) -> None:
    name = "phase3: cpu.trace_ring + cpu.traceback show the chain in order"
    try:
        _reset(agent)
        agent.call("cpu.trace_ring", depth=128, seg=cs)
        agent.debugger_command(f"BP {cs:04X}:{trace_end:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("3")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        tb = agent.call("cpu.traceback", count=32)
        entries = tb.get("entries", [])
        if not entries:
            rep.record(name, False, "empty traceback")
            return
        last = entries[-1]
        if last.get("cs_ip") != f"{cs:04X}:{trace_end:04X}":
            rep.record(name, False,
                       f"last entry {last.get('cs_ip')} != trace_end {cs:04X}:{trace_end:04X}")
            return
        offs = []
        for e in entries:
            seg_s, _, off_s = e.get("cs_ip", "").partition(":")
            offs.append((int(seg_s, 16), int(off_s, 16)))
        start_idx = None
        for i in range(len(offs) - 1, -1, -1):
            if offs[i] == (cs, trace_a):
                start_idx = i
                break
        if start_idx is None:
            rep.record(name, False,
                       f"trace_a {cs:04X}:{trace_a:04X} not in traceback tail: "
                       f"{[e['cs_ip'] for e in entries[-8:]]}")
            return
        chain = offs[start_idx:]
        ok = all(s == cs for s, _ in chain)
        ok = ok and all(chain[i][1] < chain[i + 1][1] for i in range(len(chain) - 1))
        ok = ok and chain[-1][1] == trace_end
        if not ok:
            rep.record(name, False,
                       f"chain not a monotonic run to trace_end: "
                       f"{[f'{s:04X}:{o:04X}' for s, o in chain]}")
            return
        rep.record(name, True,
                   f"{len(chain)} insns trace_a->trace_end in order, last={last.get('text')!r}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.call("cpu.trace_ring", enabled=False)
            agent.cpu_run(); _drain_events(agent)


# Must match obstest.asm's WATCH_INITIAL / WATCH_VALUE / VGA_OFFSET / VGA_VALUE.
WATCH_INITIAL = 0x0761
WATCH_VALUE = 0x0853
VGA_SEG = 0xA000
VGA_OFFSET = 0x0064
VGA_VALUE = 0x005A


def phase4_memwatch(agent, cs, watch_target, store, rep) -> None:
    # 4.9.4: arm a write-intercept on the 2-byte field with a value predicate,
    # tap '4' to run the single known store, and assert the mem.write event
    # names the storing instruction (from_cs:from_ip == landmark_store) and
    # reports the exact old->new transition. The watch does NOT halt the CPU,
    # so the event arrives asynchronously on the stream.
    name = "phase4: mem.watch names the stamp site + old/new value"
    try:
        _reset(agent)
        r = agent.call("mem.watch", seg=f"{cs:04X}",
                       lo=f"{watch_target:04X}", hi=f"{watch_target:04X}",
                       size=2, when={"new_eq": WATCH_VALUE})
        if not r.get("armed"):
            rep.record(name, False, f"mem.watch arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("4")
        ev = _wait_for_event(agent, "mem.write", timeout=8.0)

        problems = []
        if ev.get("seg") != cs or ev.get("off") != watch_target:
            problems.append(
                f"addr {ev.get('seg'):04X}:{ev.get('off'):04X} != "
                f"{cs:04X}:{watch_target:04X}")
        if ev.get("from_cs") != cs or ev.get("from_ip") != store:
            problems.append(
                f"from {ev.get('from_cs'):04X}:{ev.get('from_ip'):04X} != "
                f"store {cs:04X}:{store:04X}")
        if ev.get("old") != WATCH_INITIAL:
            problems.append(f"old={ev.get('old'):#06x} expected {WATCH_INITIAL:#06x}")
        if ev.get("new") != WATCH_VALUE:
            problems.append(f"new={ev.get('new'):#06x} expected {WATCH_VALUE:#06x}")
        if ev.get("size") != 2:
            problems.append(f"size={ev.get('size')} expected 2")
        ftext = (ev.get("from_text") or "").lower()
        if "mov" not in ftext:
            problems.append(f"from_text={ev.get('from_text')!r} (expected a mov)")

        # The hit counter must also surface in debug.status (non-event proof).
        st = agent.call("debug.status")
        memw = st.get("watches", {}).get("mem", {})
        if memw.get("hits", 0) < 1:
            problems.append(f"debug.status mem hits={memw.get('hits')}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"stamp at {cs:04X}:{store:04X} "
                       f"old={ev['old']:#06x}->new={ev['new']:#06x} "
                       f"'{ev.get('from_text')}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("mem.unwatch")
            agent.cpu_run(); _drain_events(agent)


def phase5_vga_memwatch(agent, cs, vga_store, rep) -> None:
    # 4.9.4 (VGA blind spot): the framebuffer used to be invisible to mem.watch
    # because reading it back to obtain the old value loads the VGA plane
    # latches. The hook now classifies the destination: side-effecting memory
    # (VGA/MMIO) is reported WITHOUT reading old (old==null) using only the
    # new-value predicate. Arm a watch on the single A000:VGA_OFFSET byte with
    # when new_eq=VGA_VALUE (so the mode-12h BIOS screen clear, which writes 0,
    # is filtered out), tap '5' to run the one known framebuffer store, and
    # assert the mem.write event names the storing instruction with
    # new==VGA_VALUE and old==None.
    name = "phase5: mem.watch fires on VGA framebuffer write (old=null)"
    try:
        _reset(agent)
        r = agent.call("mem.watch", seg=f"{VGA_SEG:04X}",
                       lo=f"{VGA_OFFSET:04X}", hi=f"{VGA_OFFSET:04X}",
                       size=1, when={"new_eq": VGA_VALUE})
        if not r.get("armed"):
            rep.record(name, False, f"mem.watch arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("5")
        ev = _wait_for_event(agent, "mem.write", timeout=8.0)

        problems = []
        if ev.get("seg") != VGA_SEG or ev.get("off") != VGA_OFFSET:
            problems.append(
                f"addr {ev.get('seg'):04X}:{ev.get('off'):04X} != "
                f"{VGA_SEG:04X}:{VGA_OFFSET:04X}")
        if ev.get("from_cs") != cs or ev.get("from_ip") != vga_store:
            problems.append(
                f"from {ev.get('from_cs'):04X}:{ev.get('from_ip'):04X} != "
                f"vga_store {cs:04X}:{vga_store:04X}")
        # The decisive new behaviour: old is NOT sampled for VGA memory.
        if ev.get("old") is not None:
            problems.append(f"old={ev.get('old')!r} expected null (VGA read has side effects)")
        if ev.get("new") != VGA_VALUE:
            problems.append(f"new={ev.get('new')} expected {VGA_VALUE}")
        if ev.get("size") != 1:
            problems.append(f"size={ev.get('size')} expected 1")

        # And the hit counter surfaces in debug.status (non-event proof).
        st = agent.call("debug.status")
        memw = st.get("watches", {}).get("mem", {})
        if memw.get("hits", 0) < 1:
            problems.append(f"debug.status mem hits={memw.get('hits')}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"VGA store at {cs:04X}:{vga_store:04X} "
                       f"new={ev['new']:#04x} old=null "
                       f"'{ev.get('from_text')}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("mem.unwatch")
            agent.cpu_run(); _drain_events(agent)


def phase6_multi_sentinel(agent, cs, msa, msb, rep) -> None:
    # 4.9.5: arm cpu.watch_target with a TWO-sentinel set (msa first, msb
    # second). The guest makes two NEAR calls, msa then msb. Assert each
    # cpu.transfer event carries the right `which` (0 for msa, 1 for msb),
    # names the calling segment, and that debug.status shows one hit per
    # sentinel (and 2 total). The watch does not halt the CPU, so the two
    # events arrive asynchronously on the stream.
    name = "phase6: multi-sentinel cpu.watch_target reports which + per-sentinel hits"
    try:
        _reset(agent)
        r = agent.call("cpu.watch_target",
                       targets=[f"{cs:04X}:{msa:04X}", f"{cs:04X}:{msb:04X}"])
        if not r.get("watching") or len(r.get("targets", [])) != 2:
            rep.record(name, False, f"watch_target arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("6")

        # Collect the two cpu.transfer events keyed by target_off.
        events: dict[int, dict] = {}
        deadline = time.monotonic() + 8.0
        while len(events) < 2 and time.monotonic() < deadline:
            ev = agent.next_event(timeout=max(0.05, deadline - time.monotonic()))
            if ev is None:
                continue
            if ev.get("event") == "cpu.transfer":
                events[ev.get("target_off")] = ev

        problems = []
        for idx, off in ((0, msa), (1, msb)):
            ev = events.get(off)
            if ev is None:
                problems.append(f"no cpu.transfer for sentinel {idx} ({cs:04X}:{off:04X})")
                continue
            if ev.get("which") != idx:
                problems.append(f"which={ev.get('which')} expected {idx} @ {cs:04X}:{off:04X}")
            if ev.get("target_seg") != cs:
                problems.append(f"target_seg={ev.get('target_seg'):04X} expected {cs:04X}")
            if ev.get("from_cs") != cs:
                problems.append(f"from_cs={ev.get('from_cs'):04X} expected {cs:04X}")

        # Per-sentinel hit counters in debug.status (non-event proof). The
        # guest may run phase 6 more than once if the '6' key auto-repeats
        # before the slow paste-pump releases it — a known harness timing
        # quirk that phases 4/5 also tolerate (they use >=1 thresholds). What
        # MUST hold regardless of pass count: each sentinel is counted
        # independently and *equally* (one call apiece per pass), and the
        # total is their sum.
        agent.cpu_pause(); _drain_events(agent)
        st = agent.call("debug.status")
        tgt = st.get("watches", {}).get("target", {})
        sentinels = tgt.get("sentinels", [])
        h0 = h1 = 0
        if len(sentinels) != 2:
            problems.append(f"sentinels={sentinels}")
        else:
            h0 = sentinels[0].get("hits", 0)
            h1 = sentinels[1].get("hits", 0)
            if h0 < 1 or h1 < 1:
                problems.append(f"per-sentinel hits [{h0},{h1}] (expected >=1 each)")
            if h0 != h1:
                problems.append(f"per-sentinel hits unequal [{h0},{h1}]")
            if tgt.get("hits") != h0 + h1:
                problems.append(f"total hits={tgt.get('hits')} != {h0}+{h1}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"which 0->{cs:04X}:{msa:04X}, 1->{cs:04X}:{msb:04X}; "
                       f"per-sentinel hits [{h0},{h1}]")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("cpu.unwatch_target")
            agent.cpu_run(); _drain_events(agent)


def _off_of(cs_ip: str) -> int:
    """Return the offset half of a "SEG:OFF" string as an int (masked to 16 bits
    so the step result's 32-bit EIP rendering compares against a real-mode
    landmark offset)."""
    _, _, off_s = (cs_ip or "").partition(":")
    return int(off_s, 16) & 0xFFFF if off_s else -1


def phase7_step(agent, cs, trace_a, trace_end, call_at, call_ret, sub, rep) -> None:
    # 7a: cpu.step is single-instruction granular and returns post-step regs +
    # the instruction now at CS:IP. Walk the phase-3 straight-line chain
    #   mov ax,AAAA / mov bx,BBBB / mov dx,DDDD / xchg ax,bx / inc ax / dec bx
    # one instruction at a time, asserting each register transition and that
    # every step's `insn.bytes` equals mem.read of the reported address.
    name = "phase7a: cpu.step single-steps with post-step regs + insn"
    try:
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{trace_a:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("3")
        _wait_for_event(agent, "bp.hit", timeout=8.0)

        problems = []

        def do_step():
            r = agent.call("cpu.step")
            for k in ("regs", "cs_ip", "insn"):
                if k not in r:
                    problems.append(f"step result missing {k!r}: {r}")
            insn = r.get("insn", {})
            gotbytes = (insn.get("bytes") or "").upper().split()
            csip = insn.get("cs_ip", "")
            if gotbytes and csip:
                seg_s, _, off_s = csip.partition(":")
                mem = agent.mem_read("seg:off", f"{seg_s}:{off_s}", len(gotbytes))
                if [f"{x:02X}" for x in mem] != gotbytes:
                    problems.append(f"@{csip} insn.bytes {gotbytes} != mem")
            return r["regs"], _off_of(r.get("cs_ip", ""))

        regs, off = do_step()                      # after mov ax,AAAA
        if regs["eax"] & 0xFFFF != 0xAAAA:
            problems.append(f"after step1 eax={regs['eax']:#x} (want low AAAA)")
        regs, off = do_step()                      # after mov bx,BBBB
        if regs["ebx"] & 0xFFFF != 0xBBBB:
            problems.append(f"after step2 ebx={regs['ebx']:#x} (want low BBBB)")
        regs, off = do_step()                      # after mov dx,DDDD
        if regs["edx"] & 0xFFFF != 0xDDDD:
            problems.append(f"after step3 edx={regs['edx']:#x} (want low DDDD)")
        regs, off = do_step()                      # after xchg ax,bx
        if regs["eax"] & 0xFFFF != 0xBBBB or regs["ebx"] & 0xFFFF != 0xAAAA:
            problems.append(f"after xchg eax={regs['eax']:#x} ebx={regs['ebx']:#x}")
        regs, off = do_step()                      # after inc ax
        if regs["eax"] & 0xFFFF != 0xBBBC:
            problems.append(f"after inc ax eax={regs['eax']:#x} (want low BBBC)")
        regs, off = do_step()                      # after dec bx -> now at trace_end
        if regs["ebx"] & 0xFFFF != 0xAAA9:
            problems.append(f"after dec bx ebx={regs['ebx']:#x} (want low AAA9)")
        if off != trace_end:
            problems.append(f"landed at {off:04X}, expected trace_end {trace_end:04X}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True, "6 steps; reg transitions + insn.bytes verified")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)

    # 7b: at the SAME known CALL, cpu.step descends into the subroutine
    # (lands at landmark_sub) while cpu.step_over treats the call as one unit
    # (lands at landmark_call_ret). step_over of a CALL is the asynchronous,
    # deferred-reply path: agent.call() still returns the post-step {regs}.
    name = "phase7b: cpu.step into vs cpu.step_over over a CALL"
    try:
        problems = []

        # step into the call
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{call_at:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("7")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        r = agent.call("cpu.step")
        into = _off_of(r.get("cs_ip", ""))
        if into != sub:
            problems.append(f"cpu.step landed at {into:04X}, expected sub {sub:04X}")

        # step over the call (fresh hit at the same CALL)
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{call_at:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("7")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        r = agent.call("cpu.step_over")
        over = _off_of(r.get("cs_ip", ""))
        if over != call_ret:
            problems.append(
                f"cpu.step_over landed at {over:04X}, expected call_ret {call_ret:04X}")
        if "regs" not in r:
            problems.append(f"step_over result missing regs: {r}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"step->sub {sub:04X}, step_over->call_ret {call_ret:04X}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def run(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dosbox", default=str(DEFAULT_DOSBOX))
    p.add_argument("--keep-tmp", action="store_true")
    args = p.parse_args(argv)

    dosbox_exe = pathlib.Path(args.dosbox)
    if not dosbox_exe.exists():
        print(f"ERROR: dosbox-x.exe not found at {dosbox_exe}", file=sys.stderr)
        return 2
    if not OBSTEST_COM.exists():
        print(f"ERROR: OBSTEST.COM not found at {OBSTEST_COM}. Build it via "
              "tests/agent_live/build_masm.py.", file=sys.stderr)
        return 2

    tmp = pathlib.Path(tempfile.mkdtemp(prefix="obstest_"))
    shutil.copy2(OBSTEST_COM, tmp / "OBSTEST.COM")
    portfile = tmp / "dbxport.txt"
    proc: Optional[subprocess.Popen] = None
    rep = Reporter()
    try:
        proc = _launch(dosbox_exe, tmp, portfile)
        port = _wait_for_portfile(portfile, timeout=30.0)
        print(f"DOSBox-X agent on 127.0.0.1:{port}", flush=True)
        with DbxAgent(port=port) as agent:
            ver = agent.vm_version()
            print(f"connected: version={ver['version']} build={ver['build']}", flush=True)
            if ver["build"] != "heavy-debug":
                print("WARNING: probe/trace need a heavy-debug build; this is "
                      f"{ver['build']!r}. Phases 1a/3 will likely fail.", flush=True)

            cs = _read_signature(agent)
            print(f"OBSTEST.COM CS=0x{cs:04X}", flush=True)
            tbl = agent.mem_read("seg:off", f"{cs:04X}:0103", 28)
            (loopbody, disasm, trace_a, trace_end, iters, disasm_end,
             watch_target, store, vga_store, msa, msb,
             call_at, call_ret, sub) = struct.unpack("<14H", tbl)
            print(f"landmarks: loopbody={loopbody:04X} disasm={disasm:04X} "
                  f"trace_a={trace_a:04X} trace_end={trace_end:04X} iters={iters} "
                  f"disasm_end={disasm_end:04X} watch_target={watch_target:04X} "
                  f"store={store:04X} vga_store={vga_store:04X} "
                  f"msa={msa:04X} msb={msb:04X} "
                  f"call={call_at:04X} call_ret={call_ret:04X} sub={sub:04X}", flush=True)

            phase1_probe_and_counters(agent, cs, loopbody, iters, rep)
            phase2_disasm(agent, cs, disasm, disasm_end, rep)
            phase3_traceback(agent, cs, trace_a, trace_end, rep)
            phase4_memwatch(agent, cs, watch_target, store, rep)
            phase5_vga_memwatch(agent, cs, vga_store, rep)
            phase6_multi_sentinel(agent, cs, msa, msb, rep)
            phase7_step(agent, cs, trace_a, trace_end, call_at, call_ret, sub, rep)

            with contextlib.suppress(Exception):
                _reset(agent)
                agent.cpu_run(); _drain_events(agent)
                agent.keyboard_tap("q")
        if proc is not None:
            try:
                proc.wait(timeout=10.0)
            except subprocess.TimeoutExpired:
                proc.terminate()
                with contextlib.suppress(subprocess.TimeoutExpired):
                    proc.wait(timeout=5.0)
    finally:
        if proc is not None and proc.poll() is None:
            proc.kill()
        if not args.keep_tmp:
            shutil.rmtree(tmp, ignore_errors=True)
        else:
            print(f"(kept tmp dir: {tmp})", flush=True)

    print("---")
    print(f"{sum(1 for _, ok, _ in rep.results if ok)}/{len(rep.results)} phases passed")
    return 0 if rep.all_passed else 1


if __name__ == "__main__":
    sys.exit(run())
