#!/usr/bin/env python3
"""Live-fire test for the agent observability & trust commands.

Companion to test_bps.py. Runs OBSTEST.COM inside a real DOSBox-X instance
over the agent control channel and proves, end-to-end against a running
guest, that the commands report the truth:

  Scenario 1: arm cpu.probe on the scenario-1 NOP loop body, run
     the loop (exactly LOOP_ITERS iterations), and assert debug.status shows
     the probe hit count == LOOP_ITERS — a full-speed, non-halting count.
     Then set a real BP at the same address, run, and assert it fires AND
     that debug.status reports that BP's own hit counter and live bytes_now.
     This is the C01E "fired or never reached?" disambiguation made concrete.

  Scenario 2: cpu.disasm the known, never-executed instruction block at
     landmark_disasm and check the decoded mnemonics, that every reported
     `bytes` field equals mem.read of the same address (the anti-fabrication
     guarantee), and that the walk lands exactly on disasm_end.

  Scenario 3: arm cpu.trace_ring (CS-filtered), run the distinctive
     straight-line chain, pause at a BP on landmark_trace_end, and assert
     cpu.traceback shows the chain in execution order, most-recent-last,
     ending at trace_end.

  Scenarios 4-8 cover mem.watch (VGA), multi-sentinel watches,
  cpu.step/step_over, and state.save/restore.

  Scenario 9: conditional / Nth-hit breakpoints with on-hit macros,
     reusing the scenario-1 loop (cx == iters+1-N at the Nth hit). 9a halts on the
     Nth hit and captures a regs.get macro atomically at the trigger; 9b uses a
     register condition with continue=true to fire-and-resume, proving the
     hits-vs-fires distinction.

The landmark offsets are read from a fixed table in the guest at runtime
(CS:0103), so the driver never hardcodes volatile offsets.

Usage:
    python tests/agent_live/test_observability.py [--dosbox PATH] [--keep-tmp]

Exit code 0 if every scenario passes; 1 otherwise.
"""

from __future__ import annotations

import argparse
import contextlib
import pathlib
import shutil
import struct
import subprocess
import sys
import tempfile
import textwrap
import time
from typing import Optional

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_DOSBOX = REPO_ROOT / "bin" / "x64" / "Debug" / "dosbox-x.exe"
OBSTEST_COM = pathlib.Path(__file__).resolve().with_name("OBSTEST.COM")

sys.path.insert(0, str(REPO_ROOT / "contrib" / "agent-client"))
from dbxagent import DbxAgent, AgentError  # noqa: E402

SIGNATURE_ADDR = 0x4F0
SIGNATURE_MAGIC = 0xBEEF


# --- helpers (shared shape with test_bps.py) ------------------------------

def _wait_for_portfile(path: pathlib.Path, timeout: float = 30.0) -> int:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if path.exists():
            text = path.read_text(encoding="ascii", errors="replace").strip()
            if text.isdigit():
                return int(text)
        time.sleep(0.1)
    raise TimeoutError(f"DOSBox-X never wrote {path}")


def _read_signature(agent: DbxAgent, timeout: float = 20.0) -> int:
    deadline = time.monotonic() + timeout
    last_err: Optional[Exception] = None
    while time.monotonic() < deadline:
        try:
            buf = agent.mem_read("physical", f"{SIGNATURE_ADDR:X}", 4)
        except AgentError as exc:
            last_err = exc
            time.sleep(0.1)
            continue
        magic, cs = struct.unpack("<HH", buf)
        if magic == SIGNATURE_MAGIC:
            return cs
        time.sleep(0.1)
    if last_err:
        raise last_err
    raise TimeoutError("OBSTEST.COM never stamped its signature")


def _drain_events(agent: DbxAgent) -> None:
    while agent.next_event(timeout=0.05) is not None:
        pass


def _wait_for_event(agent: DbxAgent, name: str, timeout: float = 8.0) -> dict:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        remaining = max(0.05, deadline - time.monotonic())
        ev = agent.next_event(timeout=remaining)
        if ev is None:
            continue
        if ev.get("event") == name:
            return ev
    raise TimeoutError(f"no {name!r} event within {timeout}s")


def _reset(agent: DbxAgent) -> None:
    """Pause, clear BPs + all observers, drain. Caller resumes."""
    agent.cpu_pause()
    _drain_events(agent)
    agent.debugger_command("BPDEL 0 *")
    agent.call("cpu.probe", points=[])
    with contextlib.suppress(Exception):
        agent.call("cpu.trace_ring", enabled=False)
    with contextlib.suppress(Exception):
        agent.call("mem.unwatch")
    with contextlib.suppress(Exception):
        agent.call("bp.clear")
    _drain_events(agent)


def _write_conf(workdir: pathlib.Path) -> pathlib.Path:
    conf_text = textwrap.dedent(
        f"""\
        # Generated by tests/agent_live/test_observability.py
        [sdl]
        output=surface
        autolock=false
        windowresolution=640x400

        [dosbox]
        machine=svga_s3
        memsize=16

        [cpu]
        core=normal
        cputype=486
        cycles=fixed 5000

        [autoexec]
        mount C "{workdir}"
        C:
        OBSTEST.COM
        exit
        """
    )
    conf_path = workdir / "_test.dosbox-x.conf"
    conf_path.write_text(conf_text, encoding="utf-8")
    return conf_path


def _launch(dosbox_exe, workdir, portfile) -> subprocess.Popen:
    conf = _write_conf(workdir)
    return subprocess.Popen(
        [str(dosbox_exe), "-conf", str(conf),
         "-agent-listen", "127.0.0.1:0",
         "-agent-portfile", str(portfile), "-fastlaunch"],
        cwd=str(workdir),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


class Reporter:
    def __init__(self) -> None:
        self.results: list[tuple[str, bool, str]] = []

    def record(self, name: str, ok: bool, detail: str = "") -> None:
        self.results.append((name, ok, detail))
        print(f"[{'PASS' if ok else 'FAIL'}] {name}" + (f" :: {detail}" if detail else ""),
              flush=True)

    @property
    def all_passed(self) -> bool:
        return all(ok for _, ok, _ in self.results)


# --- scenarios ---------------------------------------------------------------

def scenario1_probe_and_counters(agent, cs, loopbody, iters, rep) -> None:
    # 1a: probe counts every iteration at full speed, no halt.
    name = f"scenario1a: cpu.probe counts {iters} loop iterations (non-halting)"
    try:
        _reset(agent)
        r = agent.call("cpu.probe", points=[f"{cs:04X}:{loopbody:04X}"])
        if r.get("armed") != 1:
            rep.record(name, False, f"probe arm reply: {r}")
        else:
            agent.cpu_run()
            _drain_events(agent)
            agent.keyboard_tap("1")
            time.sleep(1.0)   # 300 short NOPs at 5000 cyc/ms — give it a beat
            agent.cpu_pause(); _drain_events(agent)
            st = agent.call("debug.status")
            probe = st.get("probe", [])
            hit = next((p for p in probe
                        if p.get("seg") == cs and p.get("off") == loopbody), None)
            if hit is None:
                rep.record(name, False, f"probe point absent from debug.status: {probe}")
            elif hit["hits"] != iters:
                rep.record(name, False, f"probe hits={hit['hits']} expected {iters}")
            else:
                rep.record(name, True, f"probe hits == {iters}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.call("cpu.probe", points=[])
            agent.cpu_run(); _drain_events(agent)

    # 1b: a real BP at the same address fires, and debug.status reports its
    # hit counter + live bytes_now (0x90 = NOP at loopbody).
    name = "scenario1b: BP hit counter + bytes_now in debug.status"
    try:
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{loopbody:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("1")
        ev = _wait_for_event(agent, "bp.hit", timeout=8.0)
        st = agent.call("debug.status")
        if st.get("cpu") != "paused":
            rep.record(name, False, f"cpu state={st.get('cpu')!r} (expected paused)")
            return
        bps = st.get("breakpoints", [])
        bp = next((b for b in bps
                   if b.get("kind") == "exec" and b.get("seg") == cs
                   and b.get("off") == loopbody), None)
        if bp is None:
            rep.record(name, False, f"exec BP absent from debug.status: {bps}")
            return
        problems = []
        if bp.get("hits", 0) < 1:
            problems.append(f"hits={bp.get('hits')}")
        bytes_now = (bp.get("bytes_now") or "").upper().split()
        if not bytes_now or bytes_now[0] != "90":
            problems.append(f"bytes_now={bp.get('bytes_now')!r} (expected first byte 90/NOP)")
        if ev.get("seg") != cs or ev.get("off") != loopbody:
            problems.append(f"bp.hit at {ev.get('seg'):04X}:{ev.get('off'):04X}")
        if problems:
            rep.record(name, False, "; ".join(problems))
        else:
            rep.record(name, True, f"hits={bp['hits']} bytes_now='{bp['bytes_now']}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def scenario2_disasm(agent, cs, disasm, disasm_end, rep) -> None:
    name = "scenario2: cpu.disasm decodes the known instruction block"
    # The fodder at landmark_disasm is, in source order:
    #   mov ax,1234h / add bx,ax / push bx / pop cx / nop / ret(n)
    # We don't hardcode exact encodings (assembler-dependent); we (a) require
    # this mnemonic sequence, (b) cross-check every instruction's reported
    # bytes against mem.read of the same address (proving cpu.disasm reads
    # guest memory rather than fabricating), and (c) require the decode to
    # land exactly on disasm_end.
    expected_mnemonics = ["mov", "add", "push", "pop", "nop", "ret"]
    try:
        _reset(agent)
        agent.cpu_run(); _drain_events(agent)   # CPU running; disasm is a pure read
        res = agent.call("cpu.disasm", addr=f"{cs:04X}:{disasm:04X}", count=12)
        insns = res.get("insns", [])
        if not insns:
            rep.record(name, False, "cpu.disasm returned no insns")
            return
        problems = []
        mnemonics = []
        off = disasm
        for ins in insns:
            if off >= disasm_end:
                break
            text = (ins.get("text") or "").lower()
            gotbytes = (ins.get("bytes") or "").upper().split()
            exp_csip = f"{cs:04X}:{off:04X}"
            if ins.get("cs_ip") != exp_csip:
                problems.append(f"cs_ip={ins.get('cs_ip')!r} expected {exp_csip}")
            try:
                mem = agent.mem_read("seg:off", f"{cs:04X}:{off:04X}", len(gotbytes))
                memhex = [f"{x:02X}" for x in mem]
            except Exception as exc:
                problems.append(f"mem.read failed at {exp_csip}: {exc!r}")
                memhex = []
            if memhex and memhex != gotbytes:
                problems.append(f"@{exp_csip} disasm bytes {gotbytes} != mem {memhex}")
            mnemonics.append(text.split()[0] if text.split() else "")
            off += len(gotbytes)
        if off != disasm_end:
            problems.append(f"walked to {off:04X}, expected disasm_end {disasm_end:04X}")
        if len(mnemonics) != len(expected_mnemonics) or \
           not all(exp in got for exp, got in zip(expected_mnemonics, mnemonics)):
            problems.append(f"mnemonics={mnemonics} expected ~{expected_mnemonics}")
        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"{len(mnemonics)} insns; bytes match mem.read; mnemonics {mnemonics}")
    except Exception as exc:
        rep.record(name, False, repr(exc))


def scenario3_traceback(agent, cs, trace_a, trace_end, rep) -> None:
    name = "scenario3: cpu.trace_ring + cpu.traceback show the chain in order"
    try:
        _reset(agent)
        agent.call("cpu.trace_ring", depth=128, seg=cs)
        agent.debugger_command(f"BP {cs:04X}:{trace_end:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("3")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        tb = agent.call("cpu.traceback", count=32)
        entries = tb.get("entries", [])
        if not entries:
            rep.record(name, False, "empty traceback")
            return
        last = entries[-1]
        if last.get("cs_ip") != f"{cs:04X}:{trace_end:04X}":
            rep.record(name, False,
                       f"last entry {last.get('cs_ip')} != trace_end {cs:04X}:{trace_end:04X}")
            return
        offs = []
        for e in entries:
            seg_s, _, off_s = e.get("cs_ip", "").partition(":")
            offs.append((int(seg_s, 16), int(off_s, 16)))
        start_idx = None
        for i in range(len(offs) - 1, -1, -1):
            if offs[i] == (cs, trace_a):
                start_idx = i
                break
        if start_idx is None:
            rep.record(name, False,
                       f"trace_a {cs:04X}:{trace_a:04X} not in traceback tail: "
                       f"{[e['cs_ip'] for e in entries[-8:]]}")
            return
        chain = offs[start_idx:]
        ok = all(s == cs for s, _ in chain)
        ok = ok and all(chain[i][1] < chain[i + 1][1] for i in range(len(chain) - 1))
        ok = ok and chain[-1][1] == trace_end
        if not ok:
            rep.record(name, False,
                       f"chain not a monotonic run to trace_end: "
                       f"{[f'{s:04X}:{o:04X}' for s, o in chain]}")
            return
        rep.record(name, True,
                   f"{len(chain)} insns trace_a->trace_end in order, last={last.get('text')!r}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.call("cpu.trace_ring", enabled=False)
            agent.cpu_run(); _drain_events(agent)


# Must match obstest.asm's WATCH_INITIAL / WATCH_VALUE / VGA_OFFSET / VGA_VALUE.
WATCH_INITIAL = 0x0761
WATCH_VALUE = 0x0853
VGA_SEG = 0xA000
VGA_OFFSET = 0x0064
VGA_VALUE = 0x005A


def scenario4_memwatch(agent, cs, watch_target, store, rep) -> None:
    # arm a write-intercept on the 2-byte field with a value predicate,
    # tap '4' to run the single known store, and assert the mem.write event
    # names the storing instruction (from_cs:from_ip == landmark_store) and
    # reports the exact old->new transition. The watch does NOT halt the CPU,
    # so the event arrives asynchronously on the stream.
    name = "scenario4: mem.watch names the stamp site + old/new value"
    try:
        _reset(agent)
        r = agent.call("mem.watch", seg=f"{cs:04X}",
                       lo=f"{watch_target:04X}", hi=f"{watch_target:04X}",
                       size=2, when={"new_eq": WATCH_VALUE})
        if not r.get("armed"):
            rep.record(name, False, f"mem.watch arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("4")
        ev = _wait_for_event(agent, "mem.write", timeout=8.0)

        problems = []
        if ev.get("seg") != cs or ev.get("off") != watch_target:
            problems.append(
                f"addr {ev.get('seg'):04X}:{ev.get('off'):04X} != "
                f"{cs:04X}:{watch_target:04X}")
        if ev.get("from_cs") != cs or ev.get("from_ip") != store:
            problems.append(
                f"from {ev.get('from_cs'):04X}:{ev.get('from_ip'):04X} != "
                f"store {cs:04X}:{store:04X}")
        if ev.get("old") != WATCH_INITIAL:
            problems.append(f"old={ev.get('old'):#06x} expected {WATCH_INITIAL:#06x}")
        if ev.get("new") != WATCH_VALUE:
            problems.append(f"new={ev.get('new'):#06x} expected {WATCH_VALUE:#06x}")
        if ev.get("size") != 2:
            problems.append(f"size={ev.get('size')} expected 2")
        ftext = (ev.get("from_text") or "").lower()
        if "mov" not in ftext:
            problems.append(f"from_text={ev.get('from_text')!r} (expected a mov)")

        # The hit counter must also surface in debug.status (non-event proof).
        st = agent.call("debug.status")
        memw = st.get("watches", {}).get("mem", {})
        if memw.get("hits", 0) < 1:
            problems.append(f"debug.status mem hits={memw.get('hits')}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"stamp at {cs:04X}:{store:04X} "
                       f"old={ev['old']:#06x}->new={ev['new']:#06x} "
                       f"'{ev.get('from_text')}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("mem.unwatch")
            agent.cpu_run(); _drain_events(agent)


def scenario5_vga_memwatch(agent, cs, vga_store, rep) -> None:
    # VGA blind spot: the framebuffer used to be invisible to mem.watch
    # because reading it back to obtain the old value loads the VGA plane
    # latches. The hook now classifies the destination: side-effecting memory
    # (VGA/MMIO) is reported WITHOUT reading old (old==null) using only the
    # new-value predicate. Arm a watch on the single A000:VGA_OFFSET byte with
    # when new_eq=VGA_VALUE (so the mode-12h BIOS screen clear, which writes 0,
    # is filtered out), tap '5' to run the one known framebuffer store, and
    # assert the mem.write event names the storing instruction with
    # new==VGA_VALUE and old==None.
    name = "scenario5: mem.watch fires on VGA framebuffer write (old=null)"
    try:
        _reset(agent)
        r = agent.call("mem.watch", seg=f"{VGA_SEG:04X}",
                       lo=f"{VGA_OFFSET:04X}", hi=f"{VGA_OFFSET:04X}",
                       size=1, when={"new_eq": VGA_VALUE})
        if not r.get("armed"):
            rep.record(name, False, f"mem.watch arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("5")
        ev = _wait_for_event(agent, "mem.write", timeout=8.0)

        problems = []
        if ev.get("seg") != VGA_SEG or ev.get("off") != VGA_OFFSET:
            problems.append(
                f"addr {ev.get('seg'):04X}:{ev.get('off'):04X} != "
                f"{VGA_SEG:04X}:{VGA_OFFSET:04X}")
        if ev.get("from_cs") != cs or ev.get("from_ip") != vga_store:
            problems.append(
                f"from {ev.get('from_cs'):04X}:{ev.get('from_ip'):04X} != "
                f"vga_store {cs:04X}:{vga_store:04X}")
        # The decisive new behaviour: old is NOT sampled for VGA memory.
        if ev.get("old") is not None:
            problems.append(f"old={ev.get('old')!r} expected null (VGA read has side effects)")
        if ev.get("new") != VGA_VALUE:
            problems.append(f"new={ev.get('new')} expected {VGA_VALUE}")
        if ev.get("size") != 1:
            problems.append(f"size={ev.get('size')} expected 1")

        # And the hit counter surfaces in debug.status (non-event proof).
        st = agent.call("debug.status")
        memw = st.get("watches", {}).get("mem", {})
        if memw.get("hits", 0) < 1:
            problems.append(f"debug.status mem hits={memw.get('hits')}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"VGA store at {cs:04X}:{vga_store:04X} "
                       f"new={ev['new']:#04x} old=null "
                       f"'{ev.get('from_text')}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("mem.unwatch")
            agent.cpu_run(); _drain_events(agent)


def scenario6_multi_sentinel(agent, cs, msa, msb, rep) -> None:
    # arm cpu.watch_target with a TWO-sentinel set (msa first, msb
    # second). The guest makes two NEAR calls, msa then msb. Assert each
    # cpu.transfer event carries the right `which` (0 for msa, 1 for msb),
    # names the calling segment, and that debug.status shows one hit per
    # sentinel (and 2 total). The watch does not halt the CPU, so the two
    # events arrive asynchronously on the stream.
    name = "scenario6: multi-sentinel cpu.watch_target reports which + per-sentinel hits"
    try:
        _reset(agent)
        r = agent.call("cpu.watch_target",
                       targets=[f"{cs:04X}:{msa:04X}", f"{cs:04X}:{msb:04X}"])
        if not r.get("watching") or len(r.get("targets", [])) != 2:
            rep.record(name, False, f"watch_target arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("6")

        # Collect the two cpu.transfer events keyed by target_off.
        events: dict[int, dict] = {}
        deadline = time.monotonic() + 8.0
        while len(events) < 2 and time.monotonic() < deadline:
            ev = agent.next_event(timeout=max(0.05, deadline - time.monotonic()))
            if ev is None:
                continue
            if ev.get("event") == "cpu.transfer":
                events[ev.get("target_off")] = ev

        problems = []
        for idx, off in ((0, msa), (1, msb)):
            ev = events.get(off)
            if ev is None:
                problems.append(f"no cpu.transfer for sentinel {idx} ({cs:04X}:{off:04X})")
                continue
            if ev.get("which") != idx:
                problems.append(f"which={ev.get('which')} expected {idx} @ {cs:04X}:{off:04X}")
            if ev.get("target_seg") != cs:
                problems.append(f"target_seg={ev.get('target_seg'):04X} expected {cs:04X}")
            if ev.get("from_cs") != cs:
                problems.append(f"from_cs={ev.get('from_cs'):04X} expected {cs:04X}")

        # Per-sentinel hit counters in debug.status (non-event proof). The
        # guest may run scenario 6 more than once if the '6' key auto-repeats
        # before the slow paste-pump releases it — a known harness timing
        # quirk that scenarios 4/5 also tolerate (they use >=1 thresholds). What
        # MUST hold regardless of pass count: each sentinel is counted
        # independently and *equally* (one call apiece per pass), and the
        # total is their sum.
        agent.cpu_pause(); _drain_events(agent)
        st = agent.call("debug.status")
        tgt = st.get("watches", {}).get("target", {})
        sentinels = tgt.get("sentinels", [])
        h0 = h1 = 0
        if len(sentinels) != 2:
            problems.append(f"sentinels={sentinels}")
        else:
            h0 = sentinels[0].get("hits", 0)
            h1 = sentinels[1].get("hits", 0)
            if h0 < 1 or h1 < 1:
                problems.append(f"per-sentinel hits [{h0},{h1}] (expected >=1 each)")
            if h0 != h1:
                problems.append(f"per-sentinel hits unequal [{h0},{h1}]")
            if tgt.get("hits") != h0 + h1:
                problems.append(f"total hits={tgt.get('hits')} != {h0}+{h1}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"which 0->{cs:04X}:{msa:04X}, 1->{cs:04X}:{msb:04X}; "
                       f"per-sentinel hits [{h0},{h1}]")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("cpu.unwatch_target")
            agent.cpu_run(); _drain_events(agent)


def _off_of(cs_ip: str) -> int:
    """Return the offset half of a "SEG:OFF" string as an int (masked to 16 bits
    so the step result's 32-bit EIP rendering compares against a real-mode
    landmark offset)."""
    _, _, off_s = (cs_ip or "").partition(":")
    return int(off_s, 16) & 0xFFFF if off_s else -1


def scenario7_step(agent, cs, trace_a, trace_end, call_at, call_ret, sub, rep) -> None:
    # 7a: cpu.step is single-instruction granular and returns post-step regs +
    # the instruction now at CS:IP. Walk the scenario-3 straight-line chain
    #   mov ax,AAAA / mov bx,BBBB / mov dx,DDDD / xchg ax,bx / inc ax / dec bx
    # one instruction at a time, asserting each register transition and that
    # every step's `insn.bytes` equals mem.read of the reported address.
    name = "scenario7a: cpu.step single-steps with post-step regs + insn"
    try:
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{trace_a:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("3")
        _wait_for_event(agent, "bp.hit", timeout=8.0)

        problems = []

        def do_step():
            r = agent.call("cpu.step")
            for k in ("regs", "cs_ip", "insn"):
                if k not in r:
                    problems.append(f"step result missing {k!r}: {r}")
            insn = r.get("insn", {})
            gotbytes = (insn.get("bytes") or "").upper().split()
            csip = insn.get("cs_ip", "")
            if gotbytes and csip:
                seg_s, _, off_s = csip.partition(":")
                mem = agent.mem_read("seg:off", f"{seg_s}:{off_s}", len(gotbytes))
                if [f"{x:02X}" for x in mem] != gotbytes:
                    problems.append(f"@{csip} insn.bytes {gotbytes} != mem")
            return r["regs"], _off_of(r.get("cs_ip", ""))

        regs, off = do_step()                      # after mov ax,AAAA
        if regs["eax"] & 0xFFFF != 0xAAAA:
            problems.append(f"after step1 eax={regs['eax']:#x} (want low AAAA)")
        regs, off = do_step()                      # after mov bx,BBBB
        if regs["ebx"] & 0xFFFF != 0xBBBB:
            problems.append(f"after step2 ebx={regs['ebx']:#x} (want low BBBB)")
        regs, off = do_step()                      # after mov dx,DDDD
        if regs["edx"] & 0xFFFF != 0xDDDD:
            problems.append(f"after step3 edx={regs['edx']:#x} (want low DDDD)")
        regs, off = do_step()                      # after xchg ax,bx
        if regs["eax"] & 0xFFFF != 0xBBBB or regs["ebx"] & 0xFFFF != 0xAAAA:
            problems.append(f"after xchg eax={regs['eax']:#x} ebx={regs['ebx']:#x}")
        regs, off = do_step()                      # after inc ax
        if regs["eax"] & 0xFFFF != 0xBBBC:
            problems.append(f"after inc ax eax={regs['eax']:#x} (want low BBBC)")
        regs, off = do_step()                      # after dec bx -> now at trace_end
        if regs["ebx"] & 0xFFFF != 0xAAA9:
            problems.append(f"after dec bx ebx={regs['ebx']:#x} (want low AAA9)")
        if off != trace_end:
            problems.append(f"landed at {off:04X}, expected trace_end {trace_end:04X}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True, "6 steps; reg transitions + insn.bytes verified")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)

    # 7b: at the SAME known CALL, cpu.step descends into the subroutine
    # (lands at landmark_sub) while cpu.step_over treats the call as one unit
    # (lands at landmark_call_ret). step_over of a CALL is the asynchronous,
    # deferred-reply path: agent.call() still returns the post-step {regs}.
    name = "scenario7b: cpu.step into vs cpu.step_over over a CALL"
    try:
        problems = []

        # step into the call
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{call_at:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("7")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        r = agent.call("cpu.step")
        into = _off_of(r.get("cs_ip", ""))
        if into != sub:
            problems.append(f"cpu.step landed at {into:04X}, expected sub {sub:04X}")

        # step over the call (fresh hit at the same CALL)
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{call_at:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("7")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        r = agent.call("cpu.step_over")
        over = _off_of(r.get("cs_ip", ""))
        if over != call_ret:
            problems.append(
                f"cpu.step_over landed at {over:04X}, expected call_ret {call_ret:04X}")
        if "regs" not in r:
            problems.append(f"step_over result missing regs: {r}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"step->sub {sub:04X}, step_over->call_ret {call_ret:04X}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def scenario8_savestate(agent, cs, trace_a, rep) -> None:
    # state.save / state.restore round-trip the whole machine. Pause at a
    # known landmark (trace_a, the scenario-3 chain head, where `mov ax,AAAA` has
    # NOT yet executed), snapshot to a slot, single-step three instructions so
    # CS:IP advances and ax/bx/dx load AAAA/BBBB/DDDD, then restore and assert
    # the CPU snapped back to the EXACT saved registers and CS:IP. Both ends
    # require the CPU paused, which it already is at the BP. Breakpoints are a
    # debugger construct and are not part of the snapshot, so we delete the BP
    # before saving to keep the stepping unambiguous.
    name = "scenario8: state.save/state.restore round-trips full CPU state"
    slot = 7   # high slot; avoids clobbering the user's slot 0/1
    try:
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{trace_a:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("3")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        agent.debugger_command("BPDEL 0 *")
        _drain_events(agent)

        problems = []
        saved = agent.regs_get()
        if saved["eip"] & 0xFFFF != trace_a:
            problems.append(
                f"paused at {saved['eip'] & 0xFFFF:04X}, expected trace_a {trace_a:04X}")

        sres = agent.state_save(slot)
        if sres.get("slot") != slot:
            problems.append(f"state.save slot={sres.get('slot')} (expected {slot})")

        # Advance: three movs -> ax=AAAA, bx=BBBB, dx=DDDD; CS:IP moves forward.
        for _ in range(3):
            agent.cpu_step()
        moved = agent.regs_get()
        if moved["eip"] & 0xFFFF == trace_a:
            problems.append("CS:IP did not advance after 3 steps")
        if moved["eax"] & 0xFFFF != 0xAAAA:
            problems.append(f"after steps eax={moved['eax']:#x} (want low AAAA)")

        # Restore: the machine must snap back to the saved point.
        r = agent.state_restore(slot)
        if "regs" not in r or "cs_ip" not in r:
            problems.append(f"state.restore result missing regs/cs_ip: {r}")
        else:
            if _off_of(r.get("cs_ip", "")) != trace_a:
                problems.append(
                    f"restore cs_ip {r.get('cs_ip')} != trace_a {trace_a:04X}")
            # Every register in the restore reply must equal the save snapshot.
            for k, want in saved.items():
                if r["regs"].get(k) != want:
                    problems.append(f"restore regs[{k}]={r['regs'].get(k)} != saved {want}")
                    break
            # The instruction now at CS:IP must match guest memory (anti-fabrication).
            insn = r.get("insn", {})
            gotbytes = (insn.get("bytes") or "").upper().split()
            csip = insn.get("cs_ip", "")
            if gotbytes and csip:
                seg_s, _, off_s = csip.partition(":")
                mem = agent.mem_read("seg:off", f"{seg_s}:{off_s}", len(gotbytes))
                if [f"{x:02X}" for x in mem] != gotbytes:
                    problems.append(f"@{csip} restore insn.bytes {gotbytes} != mem")

        # Independent confirmation: live regs read back match the snapshot, not
        # the moved-forward state.
        live = agent.regs_get()
        for k, want in saved.items():
            if live.get(k) != want:
                problems.append(f"post-restore live regs[{k}]={live.get(k)} != saved {want}")
                break

        # Decisive regression check for the restore->run crash: resume the CPU
        # and let it run for >1s. Before the fix, the savestate restore rebuilt
        # the PIC per-tick handler list and left the agent's own tickPoll slot
        # as a NULL function pointer; TIMER_AddTick() calls every handler each
        # millisecond, so the emulator died ~0.5s after resume (WER BEX64). With
        # the fix the agent repairs its tick handler after load(), so the VM
        # survives a resume-and-run and stays responsive.
        agent.cpu_run()
        _drain_events(agent)
        time.sleep(1.5)
        try:
            st = agent.call("debug.status")
            if st.get("cpu") not in ("running", "paused"):
                problems.append(f"unexpected cpu state after restore+run: {st.get('cpu')!r}")
        except Exception as exc:
            problems.append(f"VM died after restore+run (savestate crash): {exc!r}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"saved+restored at trace_a {trace_a:04X}; all 16 regs "
                       f"round-tripped (slot {slot}); survived resume+run")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def scenario9_cond_bp(agent, cs, loopbody, iters, rep) -> None:
    # conditional / Nth-hit breakpoints with on-hit command macros.
    # Reuses the scenario-1 bounded loop (`mov cx,iters` / nop@loopbody / loop):
    # at the Nth execution of loopbody, cx == iters + 1 - N (loop decrements cx
    # AFTER the nop). So a register condition and an Nth-hit condition pick the
    # SAME iteration, which lets the two sub-checks cross-validate.
    target_n = iters // 2                 # 150
    expected_cx = iters + 1 - target_n    # 151

    # 9a: halt on the Nth hit, with a regs.get macro captured atomically at the
    # trigger instant. The macro's cx must equal expected_cx (taken before the
    # `loop` that decrements it), proving the snapshot is at the trigger, and
    # the bp.cond event must say hits==N and halted==true.
    name = "scenario9a: Nth-hit conditional BP halts with atomic on-hit macro"
    try:
        _reset(agent)
        r = agent.bp_set(f"{cs:04X}:{loopbody:04X}", if_=f"hits=={target_n}",
                         do=[{"cmd": "regs.get"}], cont=False)
        if "bp_id" not in r:
            rep.record(name, False, f"bp.set reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("1")
        ev = _wait_for_event(agent, "bp.cond", timeout=8.0)

        problems = []
        if ev.get("hits") != target_n:
            problems.append(f"event hits={ev.get('hits')} expected {target_n}")
        if ev.get("halted") is not True:
            problems.append(f"halted={ev.get('halted')!r} expected True")
        if ev.get("seg") != cs or ev.get("off") != loopbody:
            problems.append(f"addr {ev.get('seg'):04X}:{ev.get('off'):04X}")
        results = ev.get("results", [])
        if not results or results[0].get("cmd") != "regs.get" or not results[0].get("ok"):
            problems.append(f"macro results={results}")
        else:
            # regs.get's result IS the register object (no "regs" wrapper; that
            # nesting is only in cpu.step's reply).
            macro_cx = results[0]["result"]["ecx"] & 0xFFFF
            if macro_cx != expected_cx:
                problems.append(f"macro cx={macro_cx:#x} expected {expected_cx:#x}")

        # The halt must be real: the CPU is paused and the counters surface.
        st = agent.call("debug.status")
        if st.get("cpu") != "paused":
            problems.append(f"cpu={st.get('cpu')!r} (expected paused)")
        cbs = st.get("cond_breakpoints", [])
        cb = cbs[0] if cbs else {}
        if cb.get("hits", 0) < target_n:
            problems.append(f"cond hits={cb.get('hits')} (< {target_n})")
        if cb.get("fires", 0) < 1:
            problems.append(f"cond fires={cb.get('fires')}")
        # Independent confirmation off the live registers.
        live_cx = agent.regs_get()["ecx"] & 0xFFFF
        if live_cx != expected_cx:
            problems.append(f"live cx={live_cx:#x} expected {expected_cx:#x}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"halted at hit {target_n} (cx={expected_cx:#x}); macro captured cx")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.bp_clear()
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)

    # 9b: a register condition with continue=true fires once (at the same
    # iteration cx==expected_cx) WITHOUT halting — proving run-and-resume, and
    # the hits-vs-fires distinction: the BP is reached every iteration (hits ==
    # iters) but its condition holds exactly once (fires == 1).
    name = "scenario9b: continue=true conditional BP runs-and-resumes (hits vs fires)"
    try:
        _reset(agent)
        r = agent.bp_set(f"{cs:04X}:{loopbody:04X}", if_=f"cx=={expected_cx:#x}",
                         cont=True)
        if "bp_id" not in r:
            rep.record(name, False, f"bp.set reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("1")

        # Collect events for a beat: exactly one bp.cond (halted false), and no
        # state.paused (we must never have halted).
        cond_events = []
        paused = False
        deadline = time.monotonic() + 3.0
        while time.monotonic() < deadline:
            e = agent.next_event(timeout=max(0.05, deadline - time.monotonic()))
            if e is None:
                continue
            if e.get("event") == "bp.cond":
                cond_events.append(e)
            elif e.get("event") == "state.paused":
                paused = True

        problems = []
        if paused:
            problems.append("CPU halted (state.paused seen) despite continue=true")
        if not cond_events:
            problems.append("no bp.cond event arrived")
        else:
            if any(e.get("halted") is not False for e in cond_events):
                problems.append("a bp.cond event had halted=True despite continue=true")
            # The first fire is always at the 150th reach (hits counts from 1).
            if cond_events[0].get("hits") != target_n:
                problems.append(f"first event hits={cond_events[0].get('hits')} expected {target_n}")

        # debug.status (read while running) proves the hits-vs-fires distinction.
        # The '1' key may auto-repeat before the slow paste pump releases it, so
        # the loop can run more than once (the same quirk scenarios 4/5/6 tolerate).
        # What MUST hold regardless of run count N: the BP fired once per run
        # (fires == N >= 1) yet was REACHED `iters` times per run, i.e.
        # hits == iters * fires. That equality is the whole point of the test.
        st = agent.call("debug.status")
        cbs = st.get("cond_breakpoints", [])
        cb = cbs[0] if cbs else {}
        fires = cb.get("fires", 0)
        hits = cb.get("hits", 0)
        if fires < 1:
            problems.append(f"cond fires={fires} (expected >=1)")
        if hits != iters * fires:
            problems.append(f"cond hits={hits} != iters*fires ({iters}*{fires})")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"fired {fires}x (hits={hits}={iters}*{fires}), never halted")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.bp_clear()
            agent.cpu_run(); _drain_events(agent)


def scenario10_regs_set_mem_write(agent, cs, scratch, rep) -> None:
    # regs.set writes named registers (validated all-or-nothing, paused-only);
    # mem.write stores raw bytes (base64 on the wire) into guest memory. Both
    # are confirmed by reading back independently. `scratch` is a RAM word in
    # OBSTEST's own segment (the scenario-4 watch target), used here only as a safe
    # writable location. No OBSTEST rebuild: this scenario needs just a paused CPU
    # and a writable RAM address. Runs last; it restores the registers it
    # clobbered before resuming so the guest is left undisturbed.
    name = "scenario10: regs.set + mem.write round-trip"
    saved = None
    try:
        _reset(agent)                       # leaves the CPU paused
        problems = []
        saved = agent.regs_get()

        # --- regs.set: set three GPRs, leave the rest alone ---
        want = {"eax": 0xDEADBEEF, "ebx": 0x12345678, "esi": 0x0000CAFE}
        rs = agent.regs_set(**want)
        if set(rs.get("set", [])) != set(want):
            problems.append(f"regs.set 'set' echo {rs.get('set')} != {sorted(want)}")
        for k, v in want.items():
            if rs.get("regs", {}).get(k) != v:
                problems.append(f"regs.set reply regs[{k}]={rs.get('regs',{}).get(k)} != {v:#x}")
        live = agent.regs_get()
        for k, v in want.items():
            if live.get(k) != v:
                problems.append(f"after regs.set live {k}={live.get(k)} != {v:#x}")
        if live.get("edi") != saved.get("edi"):
            problems.append(f"regs.set perturbed unrelated edi "
                            f"{saved.get('edi')} -> {live.get('edi')}")

        # A bad request must be rejected as bad_args AND change nothing.
        try:
            agent.regs_set(eax=0x11111111, bogusreg=1)
            problems.append("regs.set with an unknown register did not error")
        except AgentError as e:
            if e.code != "bad_args":
                problems.append(f"regs.set bad-register code={e.code} (want bad_args)")
        if agent.regs_get().get("eax") != want["eax"]:
            problems.append("a rejected regs.set still mutated eax (not atomic)")

        # --- mem.write: seg:off then aliased physical, each read back ---
        addr = f"{cs:04X}:{scratch:04X}"
        payload = bytes([0xDE, 0xAD, 0xBE, 0xEF, 0x5A, 0xA5])
        w = agent.mem_write("seg:off", addr, payload)
        if w.get("written") != len(payload):
            problems.append(f"mem.write written={w.get('written')} != {len(payload)}")
        back = bytes(agent.mem_read("seg:off", addr, len(payload)))
        if back != payload:
            problems.append(f"seg:off write/read mismatch {back!r} != {payload!r}")

        # A "physical" write at the same real-mode linear address must alias.
        phys = (cs << 4) + scratch
        payload2 = bytes([0x11, 0x22, 0x33, 0x44])
        agent.mem_write("physical", f"{phys:X}", payload2)
        back2 = bytes(agent.mem_read("seg:off", addr, len(payload2)))
        if back2 != payload2:
            problems.append(f"physical write not visible via seg:off {back2!r} != {payload2!r}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       "regs.set wrote eax/ebx/esi (others intact, bad req atomic); "
                       "mem.write seg:off+physical round-tripped")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            if saved is not None:
                agent.regs_set(**saved)     # undo the register clobber
            agent.cpu_run(); _drain_events(agent)


def scenario11_typed_breakpoints(agent, cs, loopbody, trace_a, rep) -> None:
    # bp.add / bp.list / bp.del — typed real breakpoints with STABLE handles.
    # Reuses the scenario-1 loopbody and the scenario-3 trace_a landmarks (no OBSTEST
    # rebuild). Two halves: (a) the handle stays valid as other breakpoints are
    # added/removed, and the iteration index does not; (b) the live bp.hit event
    # carries the same bp_id bp.add returned, so a hit correlates to the handle
    # the consumer created — the whole point of retiring the bp_index rough edge.

    # 11a: add three (two exec + one int), list, delete the MIDDLE one by id,
    # and confirm the survivors keep their ids while their indices shift.
    name = "scenario11a: bp.add/list/del stable handle survives reorder"
    try:
        _reset(agent)                        # paused, clean BP list
        agent.bp_del(all=True)

        a = agent.bp_add(f"{cs:04X}:{loopbody:04X}")
        b = agent.bp_add(f"{cs:04X}:{trace_a:04X}")
        c = agent.bp_add(kind="int", int_=0x21, ah=0x09)
        id_a, id_b, id_c = a["bp_id"], b["bp_id"], c["bp_id"]

        problems = []
        if not (id_a != id_b != id_c and id_a != id_c):
            problems.append(f"ids not distinct: {id_a},{id_b},{id_c}")
        if a.get("addr") != f"{cs:04X}:{loopbody:04X}":
            problems.append(f"exec addr echo {a.get('addr')!r}")
        if c.get("kind") != "int" or c.get("int") != 0x21:
            problems.append(f"int add reply {c}")

        lst = agent.bp_list()
        by_id = {bp["bp_id"]: bp for bp in lst.get("breakpoints", [])}
        if lst.get("count") != len(lst.get("breakpoints", [])):
            problems.append(f"count {lst.get('count')} != len {len(lst.get('breakpoints', []))}")
        for want in (id_a, id_b, id_c):
            if want not in by_id:
                problems.append(f"bp_id {want} missing from bp.list")
        if id_a in by_id and by_id[id_a].get("kind") != "exec":
            problems.append(f"id_a kind {by_id[id_a].get('kind')!r}")
        if id_c in by_id and by_id[id_c].get("kind") != "int":
            problems.append(f"id_c kind {by_id[id_c].get('kind')!r}")

        # Delete the middle handle; a and c must remain, b must be gone.
        d = agent.bp_del(id_b)
        if d.get("deleted") != 1:
            problems.append(f"bp.del deleted={d.get('deleted')}")
        lst2 = agent.bp_list()
        ids2 = {bp["bp_id"] for bp in lst2.get("breakpoints", [])}
        if id_a not in ids2 or id_c not in ids2:
            problems.append(f"survivor handle lost: have {sorted(ids2)} want {id_a},{id_c}")
        if id_b in ids2:
            problems.append(f"deleted handle {id_b} still listed")
        # Re-deleting the gone handle is not_found (proves it is really gone).
        try:
            agent.bp_del(id_b)
            problems.append("re-deleting a removed bp_id did not error")
        except AgentError as e:
            if e.code != "not_found":
                problems.append(f"re-delete code={e.code} (want not_found)")

        cleared = agent.bp_del(all=True)
        if agent.bp_list().get("count") != 0:
            problems.append("bp.del all left breakpoints behind")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"3 added (ids {id_a}/{id_b}/{id_c}); deleted middle by id, "
                       f"survivors kept handles; del all cleared {cleared.get('deleted')}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.bp_del(all=True)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)

    # 11b: the live bp.hit event carries the bp_id bp.add returned.
    name = "scenario11b: bp.hit event carries the stable bp_id from bp.add"
    try:
        _reset(agent)
        added = agent.bp_add(f"{cs:04X}:{loopbody:04X}")
        want_id = added["bp_id"]
        agent.cpu_run(); _drain_events(agent)
        # Tap '1' to run the scenario-1 loop and trip the BP. The '1' keytap can be
        # dropped against the slow paste pump (the same harness quirk scenarios
        # 4/5/6 tolerate), so re-tap until the bp.hit arrives. Once it fires the
        # CPU is paused and we stop; any buffered extra '1' is harmless.
        ev = None
        for _ in range(4):
            agent.keyboard_tap("1")
            try:
                ev = _wait_for_event(agent, "bp.hit", timeout=3.0)
                break
            except TimeoutError:
                continue
        if ev is None:
            raise TimeoutError("no bp.hit after retried '1' taps")

        problems = []
        if ev.get("seg") != cs or ev.get("off") != loopbody:
            problems.append(f"bp.hit at {ev.get('seg'):04X}:{ev.get('off'):04X}")
        if ev.get("bp_id") != want_id:
            problems.append(f"bp.hit bp_id={ev.get('bp_id')} != bp.add id {want_id}")
        st = agent.call("debug.status")
        if st.get("cpu") != "paused":
            problems.append(f"cpu={st.get('cpu')!r} (expected paused)")
        # The handle is still listed (a non-once BP survives the hit) with hits>=1.
        bp = next((b for b in agent.bp_list().get("breakpoints", [])
                   if b.get("bp_id") == want_id), None)
        if bp is None:
            problems.append(f"handle {want_id} gone from bp.list after hit")
        elif bp.get("hits", 0) < 1:
            problems.append(f"hits={bp.get('hits')} after the hit")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"bp.hit carried bp_id {want_id} (matches bp.add)")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.bp_del(all=True)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def scenario12_becomes_eq(agent, cs, bw_field, bw_store, rep) -> None:
    # Feature A (proposal 4.10): value-landed mem.watch. The guest settles the
    # 2-byte field bw_field to WATCH_VALUE one byte at a time (low byte, then the
    # high byte at bw_store). becomes_eq fires once on the rising edge and names
    # bw_store — even though no single store is a 2-byte write of WATCH_VALUE.

    # 12a: becomes_eq names the byte-wise writer.
    name = "scenario12a: mem.watch becomes_eq names the byte-wise writer"
    try:
        _reset(agent)
        r = agent.call("mem.watch", seg=f"{cs:04X}",
                       lo=f"{bw_field:04X}", hi=f"{bw_field + 1:04X}",
                       value_size=2, when={"becomes_eq": WATCH_VALUE})
        if not r.get("armed") or r.get("value_size") != 2:
            rep.record(name, False, f"mem.watch arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("8")
        ev = _wait_for_event(agent, "mem.write", timeout=8.0)

        problems = []
        if ev.get("seg") != cs or ev.get("off") != bw_field:
            problems.append(
                f"addr {ev.get('seg'):04X}:{ev.get('off'):04X} != unit {cs:04X}:{bw_field:04X}")
        if ev.get("from_cs") != cs or ev.get("from_ip") != bw_store:
            problems.append(
                f"from {ev.get('from_cs'):04X}:{ev.get('from_ip'):04X} != "
                f"bw_store {cs:04X}:{bw_store:04X}")
        if ev.get("new") != WATCH_VALUE:
            problems.append(f"new={ev.get('new')!r} expected {WATCH_VALUE:#06x}")
        # The high-byte store lands V; the unit was 0x0053 (low byte only) before.
        if ev.get("old") != 0x0053:
            problems.append(f"old={ev.get('old')!r} expected 0x0053 (low byte only)")
        if ev.get("size") != 1:
            problems.append(f"size={ev.get('size')} expected 1 (high-byte store width)")
        ftext = (ev.get("from_text") or "").lower()
        if "mov" not in ftext:
            problems.append(f"from_text={ev.get('from_text')!r} (expected a mov)")
        st = agent.call("debug.status")
        if st.get("watches", {}).get("mem", {}).get("hits", 0) < 1:
            problems.append("debug.status mem hits < 1")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"becomes_eq named {cs:04X}:{bw_store:04X} "
                       f"old=0x0053->new={WATCH_VALUE:#06x} size=1 '{ev.get('from_text')}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("mem.unwatch")
            agent.cpu_run(); _drain_events(agent)

    # 12b: the store-value predicate (new_eq=V, size=2) MISSES the byte-wise
    # populate — the exact false zero this feature removes. No mem.write arrives.
    name = "scenario12b: new_eq size=2 sees the false zero (no event), becomes_eq is the fix"
    try:
        _reset(agent)
        r = agent.call("mem.watch", seg=f"{cs:04X}",
                       lo=f"{bw_field:04X}", hi=f"{bw_field + 1:04X}",
                       size=2, when={"new_eq": WATCH_VALUE})
        if not r.get("armed"):
            rep.record(name, False, f"mem.watch arm reply: {r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("8")
        try:
            ev = _wait_for_event(agent, "mem.write", timeout=2.5)
            rep.record(name, False, f"unexpected mem.write (false zero not reproduced): {ev}")
            return
        except TimeoutError:
            pass
        agent.cpu_pause(); _drain_events(agent)
        st = agent.call("debug.status")
        hits = st.get("watches", {}).get("mem", {}).get("hits", 0)
        if hits != 0:
            rep.record(name, False, f"new_eq size=2 hits={hits} (expected 0)")
        else:
            rep.record(name, True, "new_eq size=2 produced 0 events for the byte-wise populate")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.call("mem.unwatch")
            agent.cpu_run(); _drain_events(agent)


def scenario13_reg_indexed_bp(agent, cs, dispatch, hdl_bad, node1, rep) -> None:
    # Feature B (proposal 4.10): a register-indexed [reg+disp] condition. The
    # walker dispatches each node via `call word ptr [si+04]`; the conditional BP
    # at landmark_dispatch halts only when the node it is about to call has the
    # bad handler: `word [si+04]==<hdl_bad>`. Before 4.10 this condition was
    # rejected at bp.set time; now it arms and halts with SI pointing at node1.
    name = "scenario13: bp.set word [si+04]==X halts on the bad dispatch (SI=node1)"
    try:
        _reset(agent)
        cond = f"word [si+04]==0x{hdl_bad:04X}"
        r = agent.bp_set(f"{cs:04X}:{dispatch:04X}", if_=cond,
                         do=[{"cmd": "regs.get"}], cont=False)
        if "bp_id" not in r:
            rep.record(name, False, f"bp.set reply: {r}")
            return
        if r.get("condition") != cond:
            rep.record(name, False, f"condition echo {r.get('condition')!r} != {cond!r}")
            return
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("9")
        ev = _wait_for_event(agent, "bp.cond", timeout=8.0)

        problems = []
        if ev.get("halted") is not True:
            problems.append(f"halted={ev.get('halted')!r} expected True")
        if ev.get("seg") != cs or ev.get("off") != dispatch:
            problems.append(
                f"addr {ev.get('seg'):04X}:{ev.get('off'):04X} != dispatch {cs:04X}:{dispatch:04X}")
        # node0 is reached first (condition false), node1 second (matches) -> hits 2.
        if ev.get("hits") != 2:
            problems.append(f"event hits={ev.get('hits')} expected 2 (node0 missed, node1 matched)")
        results = ev.get("results", [])
        if not results or results[0].get("cmd") != "regs.get" or not results[0].get("ok"):
            problems.append(f"macro results={results}")
        else:
            macro_si = results[0]["result"]["esi"] & 0xFFFF
            if macro_si != node1:
                problems.append(f"macro SI={macro_si:#06x} expected node1 {node1:#06x}")

        st = agent.call("debug.status")
        if st.get("cpu") != "paused":
            problems.append(f"cpu={st.get('cpu')!r} expected paused")
        cbs = st.get("cond_breakpoints", [])
        cb = cbs[0] if cbs else {}
        if cb.get("fires", 0) != 1:
            problems.append(f"cond fires={cb.get('fires')} expected 1")
        if cb.get("hits", 0) != 2:
            problems.append(f"cond hits={cb.get('hits')} expected 2")
        live_si = agent.regs_get()["esi"] & 0xFFFF
        if live_si != node1:
            problems.append(f"live SI={live_si:#06x} expected node1 {node1:#06x}")

        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"halted at node1 ({node1:#06x}); [si+04] selected hdl_bad {hdl_bad:#06x}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.bp_clear()
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def run(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dosbox", default=str(DEFAULT_DOSBOX))
    p.add_argument("--keep-tmp", action="store_true")
    args = p.parse_args(argv)

    dosbox_exe = pathlib.Path(args.dosbox)
    if not dosbox_exe.exists():
        print(f"ERROR: dosbox-x.exe not found at {dosbox_exe}", file=sys.stderr)
        return 2
    if not OBSTEST_COM.exists():
        print(f"ERROR: OBSTEST.COM not found at {OBSTEST_COM}. Build it via "
              "tests/agent_live/build_masm.py.", file=sys.stderr)
        return 2

    tmp = pathlib.Path(tempfile.mkdtemp(prefix="obstest_"))
    shutil.copy2(OBSTEST_COM, tmp / "OBSTEST.COM")
    portfile = tmp / "dbxport.txt"
    proc: Optional[subprocess.Popen] = None
    rep = Reporter()
    try:
        proc = _launch(dosbox_exe, tmp, portfile)
        port = _wait_for_portfile(portfile, timeout=30.0)
        print(f"DOSBox-X agent on 127.0.0.1:{port}", flush=True)
        with DbxAgent(port=port) as agent:
            ver = agent.vm_version()
            print(f"connected: version={ver['version']} build={ver['build']}", flush=True)
            if ver["build"] != "heavy-debug":
                print("WARNING: probe/trace need a heavy-debug build; this is "
                      f"{ver['build']!r}. Scenarios 1a/3 will likely fail.", flush=True)

            cs = _read_signature(agent)
            print(f"OBSTEST.COM CS=0x{cs:04X}", flush=True)
            tbl = agent.mem_read("seg:off", f"{cs:04X}:0103", 38)
            (loopbody, disasm, trace_a, trace_end, iters, disasm_end,
             watch_target, store, vga_store, msa, msb,
             call_at, call_ret, sub,
             bw_field, bw_store, dispatch, hdl_bad, node1) = struct.unpack("<19H", tbl)
            print(f"landmarks: loopbody={loopbody:04X} disasm={disasm:04X} "
                  f"trace_a={trace_a:04X} trace_end={trace_end:04X} iters={iters} "
                  f"disasm_end={disasm_end:04X} watch_target={watch_target:04X} "
                  f"store={store:04X} vga_store={vga_store:04X} "
                  f"msa={msa:04X} msb={msb:04X} "
                  f"call={call_at:04X} call_ret={call_ret:04X} sub={sub:04X} "
                  f"bw_field={bw_field:04X} bw_store={bw_store:04X} "
                  f"dispatch={dispatch:04X} hdl_bad={hdl_bad:04X} node1={node1:04X}",
                  flush=True)

            scenario1_probe_and_counters(agent, cs, loopbody, iters, rep)
            scenario2_disasm(agent, cs, disasm, disasm_end, rep)
            scenario3_traceback(agent, cs, trace_a, trace_end, rep)
            scenario4_memwatch(agent, cs, watch_target, store, rep)
            scenario5_vga_memwatch(agent, cs, vga_store, rep)
            scenario6_multi_sentinel(agent, cs, msa, msb, rep)
            scenario7_step(agent, cs, trace_a, trace_end, call_at, call_ret, sub, rep)
            # state.save/restore (scenario 8) resumes a healthy VM after restore,
            # then the conditional BPs (scenario 9) run on the same instance so the
            # "restore then arm a conditional BP" pairing is exercised end-to-end.
            scenario8_savestate(agent, cs, trace_a, rep)
            scenario9_cond_bp(agent, cs, loopbody, iters, rep)
            # Mutation surface (regs.set + mem.write); restores the
            # registers it touches before the final resume.
            scenario10_regs_set_mem_write(agent, cs, watch_target, rep)
            # Typed real breakpoints with stable handles (bp.add/list/del).
            scenario11_typed_breakpoints(agent, cs, loopbody, trace_a, rep)
            # Proposal 4.10: value-landed becomes_eq mem.watch + register-indexed
            # [si+04] bp.set condition.
            scenario12_becomes_eq(agent, cs, bw_field, bw_store, rep)
            scenario13_reg_indexed_bp(agent, cs, dispatch, hdl_bad, node1, rep)

            with contextlib.suppress(Exception):
                _reset(agent)
                agent.cpu_run(); _drain_events(agent)
                agent.keyboard_tap("q")
        if proc is not None:
            try:
                proc.wait(timeout=10.0)
            except subprocess.TimeoutExpired:
                proc.terminate()
                with contextlib.suppress(subprocess.TimeoutExpired):
                    proc.wait(timeout=5.0)
    finally:
        if proc is not None and proc.poll() is None:
            proc.kill()
        if not args.keep_tmp:
            shutil.rmtree(tmp, ignore_errors=True)
        else:
            print(f"(kept tmp dir: {tmp})", flush=True)

    print("---")
    print(f"{sum(1 for _, ok, _ in rep.results if ok)}/{len(rep.results)} scenarios passed")
    return 0 if rep.all_passed else 1


if __name__ == "__main__":
    sys.exit(run())
