#!/usr/bin/env python3
"""Live-fire test for the agent observability & trust commands (proposal 4.9).

Companion to test_bps.py. Runs OBSTEST.COM inside a real DOSBox-X instance
over the agent control channel and proves, end-to-end against a running
guest, that the proposal-4.9 commands report the truth:

  Phase 1 (4.9.1 + 4.9.2): arm cpu.probe on the phase-1 NOP loop body, run
     the loop (exactly LOOP_ITERS iterations), and assert debug.status shows
     the probe hit count == LOOP_ITERS — a full-speed, non-halting count.
     Then set a real BP at the same address, run, and assert it fires AND
     that debug.status reports that BP's own hit counter and live bytes_now.
     This is the C01E "fired or never reached?" disambiguation made concrete.

  Phase 2 (4.9.6): cpu.disasm the known, never-executed instruction block at
     landmark_disasm and check the decoded mnemonics, that every reported
     `bytes` field equals mem.read of the same address (the anti-fabrication
     guarantee), and that the walk lands exactly on disasm_end.

  Phase 3 (4.9.3): arm cpu.trace_ring (CS-filtered), run the distinctive
     straight-line chain, pause at a BP on landmark_trace_end, and assert
     cpu.traceback shows the chain in execution order, most-recent-last,
     ending at trace_end.

The landmark offsets are read from a fixed table in the guest at runtime
(CS:0103), so the driver never hardcodes volatile offsets.

Usage:
    python tests/agent_live/test_observability.py [--dosbox PATH] [--keep-tmp]

Exit code 0 if every phase passes; 1 otherwise.
"""

from __future__ import annotations

import argparse
import contextlib
import pathlib
import shutil
import struct
import subprocess
import sys
import tempfile
import textwrap
import time
from typing import Optional

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_DOSBOX = REPO_ROOT / "bin" / "x64" / "Debug" / "dosbox-x.exe"
OBSTEST_COM = pathlib.Path(__file__).resolve().with_name("OBSTEST.COM")

sys.path.insert(0, str(REPO_ROOT / "contrib" / "agent-client"))
from dbxagent import DbxAgent, AgentError  # noqa: E402

SIGNATURE_ADDR = 0x4F0
SIGNATURE_MAGIC = 0xBEEF


# --- helpers (shared shape with test_bps.py) ------------------------------

def _wait_for_portfile(path: pathlib.Path, timeout: float = 30.0) -> int:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if path.exists():
            text = path.read_text(encoding="ascii", errors="replace").strip()
            if text.isdigit():
                return int(text)
        time.sleep(0.1)
    raise TimeoutError(f"DOSBox-X never wrote {path}")


def _read_signature(agent: DbxAgent, timeout: float = 20.0) -> int:
    deadline = time.monotonic() + timeout
    last_err: Optional[Exception] = None
    while time.monotonic() < deadline:
        try:
            buf = agent.mem_read("physical", f"{SIGNATURE_ADDR:X}", 4)
        except AgentError as exc:
            last_err = exc
            time.sleep(0.1)
            continue
        magic, cs = struct.unpack("<HH", buf)
        if magic == SIGNATURE_MAGIC:
            return cs
        time.sleep(0.1)
    if last_err:
        raise last_err
    raise TimeoutError("OBSTEST.COM never stamped its signature")


def _drain_events(agent: DbxAgent) -> None:
    while agent.next_event(timeout=0.05) is not None:
        pass


def _wait_for_event(agent: DbxAgent, name: str, timeout: float = 8.0) -> dict:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        remaining = max(0.05, deadline - time.monotonic())
        ev = agent.next_event(timeout=remaining)
        if ev is None:
            continue
        if ev.get("event") == name:
            return ev
    raise TimeoutError(f"no {name!r} event within {timeout}s")


def _reset(agent: DbxAgent) -> None:
    """Pause, clear BPs + all observers, drain. Caller resumes."""
    agent.cpu_pause()
    _drain_events(agent)
    agent.debugger_command("BPDEL 0 *")
    agent.call("cpu.probe", points=[])
    with contextlib.suppress(Exception):
        agent.call("cpu.trace_ring", enabled=False)
    _drain_events(agent)


def _write_conf(workdir: pathlib.Path) -> pathlib.Path:
    conf_text = textwrap.dedent(
        f"""\
        # Generated by tests/agent_live/test_observability.py
        [sdl]
        output=surface
        autolock=false
        windowresolution=640x400

        [dosbox]
        machine=svga_s3
        memsize=16

        [cpu]
        core=normal
        cputype=486
        cycles=fixed 5000

        [autoexec]
        mount C "{workdir}"
        C:
        OBSTEST.COM
        exit
        """
    )
    conf_path = workdir / "_test.dosbox-x.conf"
    conf_path.write_text(conf_text, encoding="utf-8")
    return conf_path


def _launch(dosbox_exe, workdir, portfile) -> subprocess.Popen:
    conf = _write_conf(workdir)
    return subprocess.Popen(
        [str(dosbox_exe), "-conf", str(conf),
         "-agent-listen", "127.0.0.1:0",
         "-agent-portfile", str(portfile), "-fastlaunch"],
        cwd=str(workdir),
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )


class Reporter:
    def __init__(self) -> None:
        self.results: list[tuple[str, bool, str]] = []

    def record(self, name: str, ok: bool, detail: str = "") -> None:
        self.results.append((name, ok, detail))
        print(f"[{'PASS' if ok else 'FAIL'}] {name}" + (f" :: {detail}" if detail else ""),
              flush=True)

    @property
    def all_passed(self) -> bool:
        return all(ok for _, ok, _ in self.results)


# --- phases ---------------------------------------------------------------

def phase1_probe_and_counters(agent, cs, loopbody, iters, rep) -> None:
    # 1a: probe counts every iteration at full speed, no halt.
    name = f"phase1a: cpu.probe counts {iters} loop iterations (non-halting)"
    try:
        _reset(agent)
        r = agent.call("cpu.probe", points=[f"{cs:04X}:{loopbody:04X}"])
        if r.get("armed") != 1:
            rep.record(name, False, f"probe arm reply: {r}")
        else:
            agent.cpu_run()
            _drain_events(agent)
            agent.keyboard_tap("1")
            time.sleep(1.0)   # 300 short NOPs at 5000 cyc/ms — give it a beat
            agent.cpu_pause(); _drain_events(agent)
            st = agent.call("debug.status")
            probe = st.get("probe", [])
            hit = next((p for p in probe
                        if p.get("seg") == cs and p.get("off") == loopbody), None)
            if hit is None:
                rep.record(name, False, f"probe point absent from debug.status: {probe}")
            elif hit["hits"] != iters:
                rep.record(name, False, f"probe hits={hit['hits']} expected {iters}")
            else:
                rep.record(name, True, f"probe hits == {iters}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.call("cpu.probe", points=[])
            agent.cpu_run(); _drain_events(agent)

    # 1b: a real BP at the same address fires, and debug.status reports its
    # hit counter + live bytes_now (0x90 = NOP at loopbody).
    name = "phase1b: BP hit counter + bytes_now in debug.status"
    try:
        _reset(agent)
        agent.debugger_command(f"BP {cs:04X}:{loopbody:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("1")
        ev = _wait_for_event(agent, "bp.hit", timeout=8.0)
        st = agent.call("debug.status")
        if st.get("cpu") != "paused":
            rep.record(name, False, f"cpu state={st.get('cpu')!r} (expected paused)")
            return
        bps = st.get("breakpoints", [])
        bp = next((b for b in bps
                   if b.get("kind") == "exec" and b.get("seg") == cs
                   and b.get("off") == loopbody), None)
        if bp is None:
            rep.record(name, False, f"exec BP absent from debug.status: {bps}")
            return
        problems = []
        if bp.get("hits", 0) < 1:
            problems.append(f"hits={bp.get('hits')}")
        bytes_now = (bp.get("bytes_now") or "").upper().split()
        if not bytes_now or bytes_now[0] != "90":
            problems.append(f"bytes_now={bp.get('bytes_now')!r} (expected first byte 90/NOP)")
        if ev.get("seg") != cs or ev.get("off") != loopbody:
            problems.append(f"bp.hit at {ev.get('seg'):04X}:{ev.get('off'):04X}")
        if problems:
            rep.record(name, False, "; ".join(problems))
        else:
            rep.record(name, True, f"hits={bp['hits']} bytes_now='{bp['bytes_now']}'")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.cpu_run(); _drain_events(agent)


def phase2_disasm(agent, cs, disasm, disasm_end, rep) -> None:
    name = "phase2: cpu.disasm decodes the known instruction block"
    # The fodder at landmark_disasm is, in source order:
    #   mov ax,1234h / add bx,ax / push bx / pop cx / nop / ret(n)
    # We don't hardcode exact encodings (assembler-dependent); we (a) require
    # this mnemonic sequence, (b) cross-check every instruction's reported
    # bytes against mem.read of the same address (proving cpu.disasm reads
    # guest memory rather than fabricating), and (c) require the decode to
    # land exactly on disasm_end.
    expected_mnemonics = ["mov", "add", "push", "pop", "nop", "ret"]
    try:
        _reset(agent)
        agent.cpu_run(); _drain_events(agent)   # CPU running; disasm is a pure read
        res = agent.call("cpu.disasm", addr=f"{cs:04X}:{disasm:04X}", count=12)
        insns = res.get("insns", [])
        if not insns:
            rep.record(name, False, "cpu.disasm returned no insns")
            return
        problems = []
        mnemonics = []
        off = disasm
        for ins in insns:
            if off >= disasm_end:
                break
            text = (ins.get("text") or "").lower()
            gotbytes = (ins.get("bytes") or "").upper().split()
            exp_csip = f"{cs:04X}:{off:04X}"
            if ins.get("cs_ip") != exp_csip:
                problems.append(f"cs_ip={ins.get('cs_ip')!r} expected {exp_csip}")
            try:
                mem = agent.mem_read("seg:off", f"{cs:04X}:{off:04X}", len(gotbytes))
                memhex = [f"{x:02X}" for x in mem]
            except Exception as exc:
                problems.append(f"mem.read failed at {exp_csip}: {exc!r}")
                memhex = []
            if memhex and memhex != gotbytes:
                problems.append(f"@{exp_csip} disasm bytes {gotbytes} != mem {memhex}")
            mnemonics.append(text.split()[0] if text.split() else "")
            off += len(gotbytes)
        if off != disasm_end:
            problems.append(f"walked to {off:04X}, expected disasm_end {disasm_end:04X}")
        if len(mnemonics) != len(expected_mnemonics) or \
           not all(exp in got for exp, got in zip(expected_mnemonics, mnemonics)):
            problems.append(f"mnemonics={mnemonics} expected ~{expected_mnemonics}")
        if problems:
            rep.record(name, False, "; ".join(problems[:4]))
        else:
            rep.record(name, True,
                       f"{len(mnemonics)} insns; bytes match mem.read; mnemonics {mnemonics}")
    except Exception as exc:
        rep.record(name, False, repr(exc))


def phase3_traceback(agent, cs, trace_a, trace_end, rep) -> None:
    name = "phase3: cpu.trace_ring + cpu.traceback show the chain in order"
    try:
        _reset(agent)
        agent.call("cpu.trace_ring", depth=128, seg=cs)
        agent.debugger_command(f"BP {cs:04X}:{trace_end:04X}")
        agent.cpu_run(); _drain_events(agent)
        agent.keyboard_tap("3")
        _wait_for_event(agent, "bp.hit", timeout=8.0)
        tb = agent.call("cpu.traceback", count=32)
        entries = tb.get("entries", [])
        if not entries:
            rep.record(name, False, "empty traceback")
            return
        last = entries[-1]
        if last.get("cs_ip") != f"{cs:04X}:{trace_end:04X}":
            rep.record(name, False,
                       f"last entry {last.get('cs_ip')} != trace_end {cs:04X}:{trace_end:04X}")
            return
        offs = []
        for e in entries:
            seg_s, _, off_s = e.get("cs_ip", "").partition(":")
            offs.append((int(seg_s, 16), int(off_s, 16)))
        start_idx = None
        for i in range(len(offs) - 1, -1, -1):
            if offs[i] == (cs, trace_a):
                start_idx = i
                break
        if start_idx is None:
            rep.record(name, False,
                       f"trace_a {cs:04X}:{trace_a:04X} not in traceback tail: "
                       f"{[e['cs_ip'] for e in entries[-8:]]}")
            return
        chain = offs[start_idx:]
        ok = all(s == cs for s, _ in chain)
        ok = ok and all(chain[i][1] < chain[i + 1][1] for i in range(len(chain) - 1))
        ok = ok and chain[-1][1] == trace_end
        if not ok:
            rep.record(name, False,
                       f"chain not a monotonic run to trace_end: "
                       f"{[f'{s:04X}:{o:04X}' for s, o in chain]}")
            return
        rep.record(name, True,
                   f"{len(chain)} insns trace_a->trace_end in order, last={last.get('text')!r}")
    except Exception as exc:
        rep.record(name, False, repr(exc))
    finally:
        with contextlib.suppress(Exception):
            agent.cpu_pause(); _drain_events(agent)
            agent.debugger_command("BPDEL 0 *")
            agent.call("cpu.trace_ring", enabled=False)
            agent.cpu_run(); _drain_events(agent)


def run(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--dosbox", default=str(DEFAULT_DOSBOX))
    p.add_argument("--keep-tmp", action="store_true")
    args = p.parse_args(argv)

    dosbox_exe = pathlib.Path(args.dosbox)
    if not dosbox_exe.exists():
        print(f"ERROR: dosbox-x.exe not found at {dosbox_exe}", file=sys.stderr)
        return 2
    if not OBSTEST_COM.exists():
        print(f"ERROR: OBSTEST.COM not found at {OBSTEST_COM}. Build it via "
              "tests/agent_live/build_masm.py.", file=sys.stderr)
        return 2

    tmp = pathlib.Path(tempfile.mkdtemp(prefix="obstest_"))
    shutil.copy2(OBSTEST_COM, tmp / "OBSTEST.COM")
    portfile = tmp / "dbxport.txt"
    proc: Optional[subprocess.Popen] = None
    rep = Reporter()
    try:
        proc = _launch(dosbox_exe, tmp, portfile)
        port = _wait_for_portfile(portfile, timeout=30.0)
        print(f"DOSBox-X agent on 127.0.0.1:{port}", flush=True)
        with DbxAgent(port=port) as agent:
            ver = agent.vm_version()
            print(f"connected: version={ver['version']} build={ver['build']}", flush=True)
            if ver["build"] != "heavy-debug":
                print("WARNING: probe/trace need a heavy-debug build; this is "
                      f"{ver['build']!r}. Phases 1a/3 will likely fail.", flush=True)

            cs = _read_signature(agent)
            print(f"OBSTEST.COM CS=0x{cs:04X}", flush=True)
            tbl = agent.mem_read("seg:off", f"{cs:04X}:0103", 12)
            loopbody, disasm, trace_a, trace_end, iters, disasm_end = struct.unpack("<6H", tbl)
            print(f"landmarks: loopbody={loopbody:04X} disasm={disasm:04X} "
                  f"trace_a={trace_a:04X} trace_end={trace_end:04X} iters={iters} "
                  f"disasm_end={disasm_end:04X}", flush=True)

            phase1_probe_and_counters(agent, cs, loopbody, iters, rep)
            phase2_disasm(agent, cs, disasm, disasm_end, rep)
            phase3_traceback(agent, cs, trace_a, trace_end, rep)

            with contextlib.suppress(Exception):
                _reset(agent)
                agent.cpu_run(); _drain_events(agent)
                agent.keyboard_tap("q")
        if proc is not None:
            try:
                proc.wait(timeout=10.0)
            except subprocess.TimeoutExpired:
                proc.terminate()
                with contextlib.suppress(subprocess.TimeoutExpired):
                    proc.wait(timeout=5.0)
    finally:
        if proc is not None and proc.poll() is None:
            proc.kill()
        if not args.keep_tmp:
            shutil.rmtree(tmp, ignore_errors=True)
        else:
            print(f"(kept tmp dir: {tmp})", flush=True)

    print("---")
    print(f"{sum(1 for _, ok, _ in rep.results if ok)}/{len(rep.results)} phases passed")
    return 0 if rep.all_passed else 1


if __name__ == "__main__":
    sys.exit(run())
